### ISSUE TITLE
Import Eventbrite Events Plugin Latest Update

### ISSUE THREAD

**Issue by shesoullit** [xylusthemes/import-eventbrite-events#116]
After latest plugin update it appears to have broken the script for the Eventbrite Buy Now Button Modal Popup. Example of broken link where the code is displaying at the top of the event is included in the link below. 

https://www.dallas-nightlife.com/dallas-tx-event/dallas-whiskey-riot-2023/

**Comment by Rajat1192** [comment]
Hello @shesoullit ,

Sorry for the late reply sorry for the inconvenience. 

The displaying Ticket section issue is resolved in the latest version of the plugin. if you have still an issue please contact us **[here](https://xylusthemes.com/support/)**.
