### ISSUE TITLE
`iee_gm_apikey_input is null` in admin JS

### ISSUE THREAD

**Issue by vtwigt** [xylusthemes/import-eventbrite-events#132]
Hi team,

Since the latest 1.7.0 version of this plugin, the website for my client (which is also using the Pro version) is showing the following error in the JavaScript console, from line 159 of `/wp-content/plugins/import-eventbrite-events/assets/js/import-eventbrite-events-admin.js`:
```
iee_gm_apikey_input is null
```
This error might be related to the newly added Google Maps API key feature.

Could this please be fixed?

Let me know if any additional information is needed for debugging. Please note that I cannot provide access to the website itself.

Thank you!

**Comment by Rajat1192** [comment]
Hello @vtwigt,

Thank you for reporting this issue to us.

Would like to assure you that we are actively working on resolving it. We appreciate your patience and understanding. and we look forward to delivering an improved version in the near future.

**Comment by vtwigt** [comment]
About a month has passed and it seems like this error is still present in the latest version. Could you please prioritize this as it is resulting in errors in the JavaScript console for website visitors.

**Comment by Rajat1192** [comment]
We have successfully fixed the bug, which you can verify **[here](https://github.com/xylusthemes/import-eventbrite-events/pull/134)**. This fix will be included in the next version of the plugin, which is coming soon and will be compatible with WordPress 6.4. Thank you for your patience.
