### ISSUE TITLE
Event links do not appear when adding events manually

### ISSUE THREAD

**Issue by chateauvieux** [xylusthemes/import-eventbrite-events#28]
When adding a new event manually (i.e. not importing from eventBrite using the 'eventbrite imports' menus, but instead adding an event via the 'eventbrite events' menu), the URLs to the event (registration link, event link, organizer link...) do not show up upon event publishing.
Perhaps these are only supposed to render when events were imported from eventbrite... but it would be goods to also add this possibility for manually added (possibly non eventbrite ) events too.
Here's a sample event: https://ksapa.org/eventbrite-event/london-a-just-energy-transition/ . Although we have defined URLs, they don't show up in the Details/Organizer and Venue tiles.
Thanks

**Comment by support-xylusthemes** [comment]
Hello @chateauvieux , 

Thanks for reporting issue we will add option for eventlink in our upcoming version. 

Best Regards.

**Comment by chateauvieux** [comment]
hello, any news on that front ? Thanks

**Comment by Rajat1192** [comment]
Hello @chateauvieux ,

The event source link field was added to the plugin 1.6.3 version.
