### ISSUE TITLE
Event Time Zone not imported / displayed ?

### ISSUE THREAD

**Issue by chateauvieux** [xylusthemes/import-eventbrite-events#33]
Is there a way to show the timezone in which the event is occuring ? As the time is displayed in local timezone ? (the need is for a visitor to know what time the event will be in his/her timezone)

**Comment by chateauvieux** [comment]
any idea ? I can see from the latest plugin release notes that some support for timezone has been introduced, but I am unsure what and how to use it.
Thanks

**Comment by chateauvieux** [comment]
hello, any news on that front ? Thanks

**Comment by Rajat1192** [comment]
Hello @chateauvieux ,

Sorry for the late replay,

Currently, the plugin does not save the event's timezone in the database. but we will add this to our to-do list and added in the plugin's future release.
