### ISSUE TITLE
"Direct event link to Eventbrite" Doesn't work

### ISSUE THREAD

**Issue by rosejoshuap** [xylusthemes/import-eventbrite-events#53]
I checked the box that says "Check to enable direct event link to eventbrite instead of event detail page,"  but it is still taking me to to the event detail page.  Is this a bug or is there something else I need to do for this to work?

Thanks!

**Comment by Rajat1192** [comment]
Thank you for reaching out to us.

This is not a bug. The "Direct Link to Eventbrite" option is available in the Pro version. So will not work in the free version. You can buy the Pro version from the link below.

The link is: https://xylusthemes.com/plugins/import-eventbrite-events/
