### ISSUE TITLE
 Code Change for https

### ISSUE THREAD

**Issue by kirksmacdonald** [xylusthemes/import-eventbrite-events#8]
Hello

please can you make a slight adjustment to your code because as every time you update this app i have to manually change the code again

import-eventbrite-events/templates/iee-archive-content.php

current code
`$image_url[] = 'http://placehold.it/420x150?text=' . $image_date;`

change to

`$image_url[] = 'https://placehold.it/420x150?text=' . $image_date;`

with the original code when we view our events page the page serves unencrypted mixed content.

when we add the https to the code the page now serves as encrypted with the green padlock so could you kindly change this please so it serves https so i dont have to keep changing this when you update the app

![How to Take Screenshots in Windows 10 - Mozilla Firefox 09_05_2019 09_50_35](https://user-images.githubusercontent.com/43136181/57450332-149b8080-7256-11e9-96e9-f8fdc9a70560.png)

![How to Take Screenshots in Windows 10 - Mozilla Firefox 09_05_2019 09_54_51](https://user-images.githubusercontent.com/43136181/57450346-1d8c5200-7256-11e9-83eb-c39ce59f5e8a.png)

**Comment by iamdharmesh** [comment]
Fixed in https://github.com/xylusthemes/import-eventbrite-events/pull/9
